### ISSUE TITLE
Server administration and state

### ISSUE THREAD

**Issue by ailec-wu** [ailec-wu/OpenAnswer#6]
Server currently fails to logs users out on restart, so a way to log out all users or otherwise prevent glitches from occurring is needed.

Server also needs basic administrative tools.

**Comment by bahrom-matyakubov** [comment]
To unauthorize everyone on a restart, just change the secret key in config.py and restart gunicorn. At some point we should stop calling it 'secret', move it to an environment variable and source it from there.

Server now also has basic admin tools via flask-admin, see commits:
0adfed4ba4ac799cc7eb3bf8ea3a519cb683175b
4abcf3d6274f5a5b187a00edcdd9ae3624bacb6c
ceb186c9dc244765601c1de0269e76e28998413c
29a5ce922238c206f491c03a23d6b825f0ec3a0c
